name: Java CI with Maven
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: List files in directory
        run: ls -R
      - name: Build with Maven
        run: mvn -B clean package -f --mvn/pom.xml
        
  <project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
  http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion> <groupId>com.example</groupId>
  <artifactId>my-project</artifactId> <version>1.0.0</version>

  <properties> <maven.compiler.source>11</maven.compiler.source>
  <maven.compiler.target>11</maven.compiler.target> </properties>

  </project>


