name: Java CI with Maven
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: List files in directory
        run: ls -R
      - name: Build with Maven
        run: mvn -B clean package -f --mvn/pom.xml
        
   <project xmlns="http://maven.apache.org/POM/4.0.0"
   
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
  http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion> <groupId>com.example</groupId>
  <artifactId>my-project</artifactId> <version>1.0.0</version>
  <packaging>jar</packaging> <!-- or war, or pom, etc. -->

  <!-- Define dependencies here --> <dependencies> <!-- Example dependency -->
  <dependency> <groupId>org.apache.commons</groupId>
  <artifactId>commons-lang3</artifactId> <version>3.12.0</version> </dependency>
  <!-- Add more dependencies as needed --> </dependencies>

  <!-- Define plugins here --> <build> <plugins> <!-- Example plugin -->
  <plugin> <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId> <version>3.8.1</version>
  <configuration> <source>11</source> <target>11</target> </configuration>
  </plugin> <!-- Add more plugins as needed --> </plugins> </build>

  </project>


